stages:
  get_data:
    cmd: python scripts/data.py
    deps:
    - scripts/data.py
    params:
    - index_col
    outs:
    - data/initial_data.csv
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
    - models/fitted_model.pkl
    - scripts/evaluate.py
    params:
    - index_col
    - target_col
    - n_splits
    - n_jobs
    - metrics
    outs:
    - cv_results/cv_res.json
